// Production-grade webhook server (cses-pre 接入用)
//
// 不依赖 LocalBackend (lbug native 在某些环境无法启动)
// 直接挂 mountWebhookRoutes + issueTrigger，pipeline 用注入的 deps
//
// 业务仓还没 GitNexus 索引时 S3-S5 用 mock，S2 真 normalize / S6 真 K8s / S7 真 GitLab
//
// 启动:
//   npx tsx scripts/start-webhook-server.ts
//
// env:
//   GITNEXUS_GITLAB_SECRET    必需 - webhook 验签
//   GITNEXUS_AUTOPR_TOKEN     必需 - GitLab PAT
//   GITLAB_API_BASE           默认 http://git.yundiz.com/api/v4
//   JAEGER_QUERY_BASE         默认 http://192.168.6.66:32281
//   GITNEXUS_AUTOPR_LIVE      默认 0 (dryRun); =1 真发 MR
//   GITNEXUS_PROVIDER         默认 gitlab
//   PORT                      默认 3034

import express from 'express';
import { mountWebhookRoutes } from '../src/server/webhook/handler.js';
import { handleIssueOpened } from '../src/core/observability/issue-handler.js';
import { runPipeline } from '../src/core/pipeline/orchestrator.js';
import { runAutoPR } from '../src/core/auto-pr/auto-pr.js';
import { GitLabPRProvider } from '../src/core/auto-pr/providers/gitlab.js';
import { PreviewJobManager } from '../src/core/preview/preview-job-manager.js';
import {
  validateInPreview,
  checkPreviewStatus,
} from '../src/core/preview/mcp-handlers.js';
import { normalizeJaegerSpan } from '../src/core/observability/jaeger-span-normalizer.js';
import type { OrchestratorDeps } from '../src/core/pipeline/types.js';

const SECRET = process.env.GITNEXUS_GITLAB_SECRET ?? '';
const TOKEN = process.env.GITNEXUS_AUTOPR_TOKEN ?? '';
const API_BASE = process.env.GITLAB_API_BASE ?? 'http://git.yundiz.com/api/v4';
const PORT = Number(process.env.PORT ?? 3034);
const PROVIDER_KIND = process.env.GITNEXUS_PROVIDER ?? 'gitlab';

if (!SECRET) {
  console.error('FATAL: GITNEXUS_GITLAB_SECRET env required');
  process.exit(1);
}
if (!TOKEN) {
  console.error('FATAL: GITNEXUS_AUTOPR_TOKEN env required');
  process.exit(1);
}

const provider = new GitLabPRProvider({ token: TOKEN, apiBase: API_BASE });
const previewMgr = new PreviewJobManager({ maxConcurrent: 3, autoReaper: true });

// ─── 业务仓未索引前：S2 真 normalize / S3-S5 兜底 mock ─────────
const deps: OrchestratorDeps = {
  resolveSpan: async (span) => {
    const norm = normalizeJaegerSpan(span);
    return {
      resolved: true,
      handler: {
        uid: norm.contractId
          ? `Method:${norm.contractId.replace(/[^a-zA-Z0-9]/g, '_').slice(0, 60)}`
          : `Method:Unknown_${(span as any).spanID?.slice(0, 6) ?? 'x'}`,
        filePath: norm.topFrame?.file ?? 'src/main/java/Unknown.java',
        name: norm.contractId ?? 'unknown',
      },
      kind: norm.kind ?? 'http',
      contractId: norm.contractId,
      topFrame: norm.topFrame,
    } as any;
  },
  apiBlastRadius: async (p) => ({
    target_uid: p.target_uid,
    files: ['Handler.java', 'Service.java'],
    note: 'mock - 业务仓未 GitNexus 索引',
  }),
  regressionForensics: async (p) => ({
    suspects: [],
    spanCount: p.spans.length,
    note: 'mock - 业务仓未 GitNexus 索引',
  }),
  genE2ETests: async (p) => ({
    target_uid: p.target_uid,
    files: [
      { path: 'src/test/java/AutoGeneratedTest.java' },
    ],
    note: 'mock - R-1 scaffold + TODO 占位',
  }),
  validateInPreview: async (p) =>
    validateInPreview(previewMgr, p as any) as any,
  checkPreviewStatus: async (p) =>
    checkPreviewStatus(previewMgr, p as any) as any,
  autoPR: async (p) =>
    await runAutoPR({
      candidate: p.candidate,
      provider,
      dryRun: !!p.dryRun,
      stage6Pass: !!p.stage6Pass,
    }),
};

const app = express();

// 健康探活
app.get('/health', (_req, res) =>
  res.json({
    ok: true,
    service: 'gitnexus-webhook-server',
    routes: ['/webhook', '/webhook/gitlab', '/health'],
    provider: PROVIDER_KIND,
    apiBase: API_BASE,
    liveMode: process.env.GITNEXUS_AUTOPR_LIVE === '1',
  }),
);

mountWebhookRoutes(app, {
  gitlabSecret: SECRET,
  trigger: async () => ({ jobId: 'noop', status: 'ignored' }),
  issueTrigger: async (event) => {
    console.log(
      `[issue] ${event.fullName} #${event.issueNumber} labels=${(event.issueLabels ?? []).join(',')}`,
    );
    const r = await handleIssueOpened(
      {
        fullName: event.fullName,
        issueNumber: event.issueNumber!,
        issueTitle: event.issueTitle!,
        issueBody: event.issueBody!,
        issueLabels: event.issueLabels!,
      },
      {
        runPipeline: async (input) => {
          console.log(
            `  → pipeline spans=${input.spans.length} preview=${!!input.preview} prTarget=${!!input.prTarget} dryRun=${input.prTarget?.dryRun}`,
          );
          return await runPipeline(input, deps);
        },
        postIssueComment: async (a) => await provider.postIssueComment(a),
      },
    );
    console.log(
      `  ← handler ok=${r.ok} pipelineStarted=${r.pipelineStarted} commentUrl=${r.commentUrl}`,
    );
    return {
      ok: r.ok,
      pipelineStarted: r.pipelineStarted,
      reason: r.reason,
      commentUrl: r.commentUrl,
    };
  },
});

const server = app.listen(PORT, '0.0.0.0', () => {
  console.log(
    '═══════════════════════════════════════════════════════════',
  );
  console.log(
    `🚀 GitNexus webhook server (cses-pre) listening on 0.0.0.0:${PORT}`,
  );
  console.log(
    '═══════════════════════════════════════════════════════════',
  );
  console.log(`  health   GET  http://localhost:${PORT}/health`);
  console.log(`  webhook  POST http://localhost:${PORT}/webhook (alias)`);
  console.log(`  webhook  POST http://localhost:${PORT}/webhook/gitlab`);
  console.log('');
  console.log(`  provider     ${PROVIDER_KIND}`);
  console.log(`  apiBase      ${API_BASE}`);
  console.log(`  jaegerBase   ${process.env.JAEGER_QUERY_BASE ?? 'unset'}`);
  console.log(
    `  autoPRLive   ${process.env.GITNEXUS_AUTOPR_LIVE === '1' ? '✅ LIVE 真发' : '⚠️ dryRun (默认安全)'}`,
  );
  console.log(
    '═══════════════════════════════════════════════════════════',
  );
});

process.on('SIGTERM', () => {
  console.log('SIGTERM, shutting down...');
  server.close();
  previewMgr.dispose();
});
process.on('SIGINT', () => {
  console.log('SIGINT, shutting down...');
  server.close();
  previewMgr.dispose();
  process.exit(0);
});
